---
sudo: false
language: cpp
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
script:
  - mkdir _build
  - cd _build
  - cmake -DCMAKE_CXX_FLAGS="-DRVO_OUTPUT_TIME_AND_POSITIONS=0 -DRVO_SEED_RANDOM_NUMBER_GENERATOR=0" ..
  - ctest --extra-verbose --dashboard Experimental .
