---
version: 2.0.2.{build}
os:
  - Visual Studio 2013
  - Visual Studio 2015
build_script:
  - md _build
  - cd _build
  - cmake -A x64 -DCMAKE_CXX_FLAGS="/DRVO_OUTPUT_TIME_AND_POSITIONS=0 /DRVO_SEED_RANDOM_NUMBER_GENERATOR=0" ..
  - ctest --build-config Release --extra-verbose --dashboard Experimental .
test: off
